import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2e3230",
        "primary-fixed-dim": "#8ecf9e",
        "surface-container-low": "#f5f1ea",
        "surface-variant": "#e4e0d8",
        "on-error-container": "#690005",
        "outline-variant": "#c4c8bc",
        "on-surface-variant": "#4a4e4a",
        "error": "#b83230",
        "surface-dim": "#dbd7cf",
        "on-surface": "#2e3230",
        "secondary": "#6b6358",
        "outline": "#74796e",
        "primary-container": "#78a886",
        "error-container": "#ffdad8",
        "on-secondary-fixed": "#1e1a13",
        "on-primary-container": "#d8f0de",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#dcc48e",
        "on-tertiary-fixed-variant": "#554020",
        "on-primary-fixed-variant": "#2a6038",
        "on-tertiary-container": "#554020",
        "on-background": "#2e3230",
        "on-tertiary": "#ffffff",
        "background": "#faf6f0",
        "on-secondary-container": "#5e5548",
        "surface": "#faf6f0",
        "on-primary-fixed": "#002110",
        "tertiary-fixed": "#f8e0a8",
        "primary-fixed": "#c8e8d0",
        "on-secondary-fixed-variant": "#4a4538",
        "surface-tint": "#4a7c59",
        "surface-bright": "#faf6f0",
        "tertiary-container": "#c4a66a",
        "inverse-on-surface": "#f5f0e8",
        "secondary-fixed-dim": "#d4ccbf",
        "secondary-fixed": "#f0e8db",
        "primary": "#4a7c59",
        "on-error": "#ffffff",
        "secondary-container": "#f0e8db",
        "surface-container-highest": "#e4e0d8",
        "inverse-primary": "#8ecf9e",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#705c30",
        "surface-container-high": "#eae6de",
        "surface-container": "#f0ece4",
        "on-tertiary-fixed": "#221a05",
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "2xl": "2rem",
        "full": "9999px",
      },
      fontFamily: {
        headline: ["Literata", "serif"],
        display: ["Literata", "serif"],
        body: ["Nunito Sans", "sans-serif"],
        label: ["Nunito Sans", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};

export default config;
